In [2]:
import pandas as pd

white = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep=';')
red = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=';')

In [6]:
#to examine data: .head(), .tail(), .sample(), .describe(), .info(), .isnull()
white.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [7]:
#visualization
import numpy as np
print(np.histogram(red.alcohol, bins=[7,8,9,10,11,12,13,14,15]))
print(np.histogram(white.alcohol, bins=[7,8,9,10,11,12,13,14,15]))

(array([  0,   7, 673, 452, 305, 133,  21,   8], dtype=int64), array([ 7,  8,  9, 10, 11, 12, 13, 14, 15]))
(array([   0,  317, 1606, 1256,  906,  675,  131,    7], dtype=int64), array([ 7,  8,  9, 10, 11, 12, 13, 14, 15]))


In [8]:
red['type'] = 1 
white['type'] = 0
wines = red.append(white, ignore_index=True)

In [10]:
from sklearn.model_selection import train_test_split

# Specify the data 
X=wines.iloc[:,0:11]

# Specify the target labels and flatten the array 
y=np.ravel(wines.type)

# Split the data up in train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
#standardization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
# Import `Sequential` from `keras.models`
from keras.models import Sequential

# Import `Dense` from `keras.layers`
from keras.layers import Dense

# Initialize the constructor
model = Sequential()

# Add an input layer 
model.add(Dense(12, activation='relu', input_shape=(11,)))

# Add one hidden layer 
model.add(Dense(8, activation='relu'))

# Add an output layer 
model.add(Dense(1, activation='sigmoid'))

In [13]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
                   
model.fit(X_train, y_train,epochs=20, batch_size=1, verbose=1)

Epoch 1/20
4352/4352 [==============================] - 18s 1ms/step - loss: 0.3175 - accuracy: 0.8734
Epoch 2/20
4352/4352 [==============================] - 4s 1ms/step - loss: 0.0192 - accuracy: 0.9966
Epoch 3/20
4352/4352 [==============================] - 4s 1ms/step - loss: 0.0164 - accuracy: 0.9979
Epoch 4/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0257 - accuracy: 0.9947
Epoch 5/20
4352/4352 [==============================] - 5s 1ms/step - loss: 0.0139 - accuracy: 0.9968
Epoch 6/20
4352/4352 [==============================] - 4s 983us/step - loss: 0.0163 - accuracy: 0.9966
Epoch 7/20
4352/4352 [==============================] - 4s 986us/step - loss: 0.0147 - accuracy: 0.9973
Epoch 8/20
4352/4352 [==============================] - 4s 941us/step - loss: 0.0149 - accuracy: 0.9970
Epoch 9/20
4352/4352 [==============================] - 4s 1ms/step - loss: 0.0099 - accuracy: 0.9981
Epoch 10/20
4352/4352 [==============================] - 4s 1ms/step - loss

In [14]:
y_pred = model.predict(X_test)

In [21]:
#y_pred[:5]
y_test[:5]

array([0, 1, 0, 0, 0], dtype=int64)

In [19]:
#evaluate - prints loss and accuracy
score = model.evaluate(X_test, y_test,verbose=1)

print(score)

68/68 [==============================] - 1s 1ms/step - loss: 0.0279 - accuracy: 0.9949
[0.027893556281924248, 0.9948717951774597]


In [23]:
#evaluate further with these
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score
#confusion_matrix(y_test, y_pred)