<a href="https://colab.research.google.com/github/DJ-python/mit-futuremakers/blob/main/Daily%20Practice/UpSampling2DPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D

X = asarray([[4, 7],
			 [9, 14]])
print(X)

X = X.reshape((1, 2, 2, 1))

model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))
model.add(UpSampling2D(size = (4,4)))

model.summary()

yhat = model.predict(X)

yhat = yhat.reshape((16, 16))

print(yhat)

[[ 4  7]
 [ 9 14]]
Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_10 (UpSampling (None, 4, 4, 1)           0         
_________________________________________________________________
up_sampling2d_11 (UpSampling (None, 16, 16, 1)         0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[ 4.  4.  4.  4.  4.  4.  4.  4.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 4.  4.  4.  4.  4.  4.  4.  4. 

In [19]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import Conv2D

model = Sequential()
model.add(Dense(128 * 5 * 5, input_dim=100))
model.add(Reshape((5, 5, 128)))
model.add(UpSampling2D())
model.add(Conv2D(1, (3,3), padding='same'))

model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_12 (UpSampling (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


In [20]:
# example of using the transpose convolutional layer
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose

X = asarray([[21, 32],
			 [33, 46]])

print(X)

X = X.reshape((1, 2, 2, 1))

model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
model.summary()
weights = [asarray([[[[1]]]]), asarray([0])]
model.set_weights(weights)
yhat = model.predict(X)
yhat = yhat.reshape((4, 4))
print(yhat)

[[21 32]
 [33 46]]
Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[21.  0. 32.  0.]
 [ 0.  0.  0.  0.]
 [33.  0. 46.  0.]
 [ 0.  0.  0.  0.]]


In [21]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import Conv2DTranspose
from keras.layers import Conv2D

model = Sequential()
model.add(Dense(128 * 5 * 5, input_dim=100))
model.add(Reshape((5, 5, 128)))
model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
